name: goblin-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  goblin-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout rpetit3/goblin
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: goblin
          auto-activate-base: false

      - name: Setup goblin Environment
        run: |
          conda install -y -c conda-forge -c bioconda rich-click executor 'python>=3.7' cd-hit biopython ncbi-genome-download

      - name: Environment Information
        run: uname -a && env

      - name: Test goblin basics
        run: |
          echo "Testing goblin"
          bin/goblin --version
          bin/goblin --help
          bin/goblin --check

      - name: Test goblin
        run: |
          echo "Tax ID"
          bin/goblin --query 1280 --prefix saureus-taxid --limit 10 --force
          cat saureus-taxid/goblin-summary.json
          echo "Name"
          bin/goblin --query "Staphylococcus aureus" --prefix saureus-name --limit 10 --force
          cat saureus-name/goblin-summary.json
          echo "Accessions"
          bin/goblin --query test/accessions.txt --prefix saureus-accessions --force
          cat saureus-accessions/goblin-summary.tsv
